baseURL = 'https://jed-harwood.github.io/jed-harwood.github.io'
languageCode = 'en-us'
title = 'Jedidiah Harwood'
theme = 'barks'

[params.social]
    [params.social.email]
        name = "E-Mail"
        class = "fas fa-envelope"
        url = "mailto:jedharwood@ucdavis.edu"
        weight = 1
    [params.social.github]
        name = "GitHub"
        class = "fab fa-github"
        url = "https://github.com/jed-harwood"
        weight = 2
    [params.social.google_scholar]
        name = "Google Scholar"
        class = "ai ai-google-scholar-square"
        url = "https://scholar.google.com/citations?user=FXRp_1IAAAAJ&hl=en&oi=ao"
        weight = 3
    [params.social.linkedin]
        name = "LinkedIn"
        class = "fab fa-linkedin-in"
        url = "https://linkedin.com/in/jed-harwood"
        weight = 4

[params.navigation]
    show_navigation = true

[params.footer]
    show_footer = true
